---
- name: Configure infrastructure and automate application
  hosts: local
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Deploy a custom index.html
      copy:
        content: "<h1>Deployed by Ansible — Secure Task Manager Infra</h1>"
        dest: /var/www/html/index.html
